imports:
  - { resource: parameters.yml }
  - { resource: security.yml }

parameters:
  jms_serializer.camel_case_naming_strategy.class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy

framework:
  #esi:       ~
  translator:    { fallback: %locale% }
  secret:      %secret%
  router:
    resource: "%kernel.root_dir%/config/routing.yml"
    strict_requirements: %kernel.debug%
  form:
    csrf_protection: false
  validation:    { enable_annotations: true }
  templating:
    engines: ['twig']
    #assets_version: SomeVersionScheme
  default_locale:  "%locale%"
  trusted_proxies: ~
  session:     true
  fragments:     ~

# Twig Configuration
twig:
  debug:      %kernel.debug%
  strict_variables: %kernel.debug%
  exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'

# Assetic Configuration
assetic:
  debug:      %kernel.debug%
  use_controller: false
  bundles:    [ ]
  #java: /usr/bin/java
  filters:
    cssrewrite: ~
    #closure:
    #  jar: %kernel.root_dir%/Resources/java/compiler.jar
    #yui_css:
    #  jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Swiftmailer Configuration
swiftmailer:
  transport: %mailer_transport%
  host:    %mailer_host%
  username:  %mailer_user%
  password:  %mailer_password%
  spool:   { type: memory }

fos_rest:
  disable_csrf_role: ROLE_USER
  param_fetcher_listener: true
  view:
    mime_types:
      json: ['application/json', 'application/json;version=1.0', 'application/json;version=1.1', 'application/json;version=1.2']
    view_response_listener: 'force'
    formats:
      xml:  true
      json: true
    templating_formats:
      html: true
  format_listener:
    rules:
      - { path: ^/, priorities: [ html, json, xml ], fallback_format: ~, prefer_extension: true }
    media_type:
      version_regex: '/(v|version)=(?P<version>[0-9\.]+)/'
  exception:
    codes:
      'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
      'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
    messages:
      'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
  allowed_methods_listener: true
  access_denied_listener:
    json: true
  body_listener: true
  routing_loader:
    default_format: json
    include_format: true

fos_http_cache:
  cache_control:
    rules:
      # the controls section values are used in a call to Response::setCache();
      -
        match:
          path: ^/notes
          methods: [GET, HEAD]
        headers:
          cache_control: { public: true, max_age: 15, s_maxage: 30 }
          last_modified: "-1 hour"
          vary: [Accept-Encoding, Accept-Language]

doctrine_mongodb:
  connections:
    default:
      server: mongodb://%mongodb_host%
      options: {}
  default_database: server
  document_managers:
    default:
      auto_mapping: true

monolog:
  handlers:
    main:
      formatter: map.log_formatter

nelmio_cors:
  defaults:
    allow_credentials: false
    allow_origin: []
    allow_headers: []
    allow_methods: []
    expose_headers: []
    max_age: 0
    hosts: []
    origin_regex: false
  paths:
    '^/api/':
      allow_credentials: true
      allow_origin: ['*']
      allow_headers: ['*']
      allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
      max_age: 3600

lexik_jwt_authentication:
  private_key_path: %key_folder%/private.pem
  public_key_path:  %key_folder%/public.pem
  token_ttl:        86400
  pass_phrase:      %jwt_key_pass_phrase%